table dim_date
	dataCategory: Time

	column Date
		dataType: dateTime
		formatString: Short Date
		isKey
		summarizeBy: none
		sourceColumn: Date

	column year
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: year

	column quarter
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: quarter

	column month
		dataType: int64
		formatString: 0
		isHidden
		summarizeBy: none
		sourceColumn: month

	column month_name
		dataType: string
		sortByColumn: month
		summarizeBy: none
		sourceColumn: month_name

	column year_month
		dataType: string
		summarizeBy: none
		sourceColumn: year_month

	column weekday
		dataType: string
		summarizeBy: none
		sourceColumn: weekday

	partition dim_date = m
		mode: import
		source =
				let
				    Raw = if Text.StartsWith(DataFolder, "http")
				        then Web.Contents(DataFolder & "dim_date.csv.gz")
				        else File.Contents(DataFolder & "dim_date.csv.gz"),
				    Parsed = Csv.Document(
				        Binary.Decompress(Raw, Compression.GZip),
				        [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]
				    ),
				    Promoted = Table.PromoteHeaders(Parsed, [PromoteAllScalars = true]),
				    Renamed = Table.RenameColumns(Promoted, {{"date_key", "Date"}}),
				    Typed = Table.TransformColumnTypes(
				        Renamed,
				        {
				            {"Date", type date},
				            {"year", Int64.Type},
				            {"quarter", Int64.Type},
				            {"month", Int64.Type},
				            {"month_name", type text},
				            {"year_month", type text},
				            {"weekday", type text}
				        },
				        "en-US"
				    ),
				    Result = Typed
				in
				    Result
