table fact_reviews

	column review_id
		dataType: string
		isHidden
		summarizeBy: none
		sourceColumn: review_id

	column order_id
		dataType: string
		isHidden
		summarizeBy: none
		sourceColumn: order_id

	column review_score
		dataType: int64
		formatString: 0
		summarizeBy: average
		sourceColumn: review_score

	column review_date
		dataType: dateTime
		formatString: Short Date
		summarizeBy: none
		sourceColumn: review_date

	column comment_message
		dataType: string
		summarizeBy: none
		sourceColumn: comment_message

	column review_key
		dataType: string
		isHidden
		summarizeBy: none
		sourceColumn: review_key

	partition fact_reviews = m
		mode: import
		source =
				let
				    Raw = if Text.StartsWith(DataFolder, "http")
				        then Web.Contents(DataFolder & "fact_reviews.csv.gz")
				        else File.Contents(DataFolder & "fact_reviews.csv.gz"),
				    Parsed = Csv.Document(
				        Binary.Decompress(Raw, Compression.GZip),
				        [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]
				    ),
				    Promoted = Table.PromoteHeaders(Parsed, [PromoteAllScalars = true]),
				    Typed = Table.TransformColumnTypes(
				        Promoted,
				        {
				            {"review_id", type text},
				            {"order_id", type text},
				            {"review_score", Int64.Type},
				            {"review_date", type date},
				            {"comment_message", type text}
				        },
				        "en-US"
				    ),
				    WithKey = Table.AddColumn(Typed, "review_key", each [review_id] & "|" & [order_id], type text),
				    Result = WithKey
				in
				    Result
