table review_ai_labels

	column review_id
		dataType: string
		isHidden
		summarizeBy: none
		sourceColumn: review_id

	column order_id
		dataType: string
		isHidden
		summarizeBy: none
		sourceColumn: order_id

	column sentiment
		dataType: string
		summarizeBy: none
		sourceColumn: sentiment

	column topic
		dataType: string
		summarizeBy: none
		sourceColumn: topic

	column urgency
		dataType: string
		summarizeBy: none
		sourceColumn: urgency

	column summary_en
		dataType: string
		summarizeBy: none
		sourceColumn: summary_en

	column provider
		dataType: string
		summarizeBy: none
		sourceColumn: provider

	column review_key
		dataType: string
		isHidden
		summarizeBy: none
		sourceColumn: review_key

	column Stars = RELATED ( fact_reviews[review_score] )
		dataType: int64
		summarizeBy: none

	column 'Review text' = RELATED ( fact_reviews[comment_message] )
		dataType: string
		summarizeBy: none

	partition review_ai_labels = m
		mode: import
		source =
				let
				    Raw = if Text.StartsWith(DataFolder, "http")
				        then Web.Contents(DataFolder & "review_ai_labels.csv.gz")
				        else File.Contents(DataFolder & "review_ai_labels.csv.gz"),
				    Parsed = Csv.Document(
				        Binary.Decompress(Raw, Compression.GZip),
				        [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]
				    ),
				    Promoted = Table.PromoteHeaders(Parsed, [PromoteAllScalars = true]),
				    Typed = Table.TransformColumnTypes(
				        Promoted,
				        {
				            {"review_id", type text},
				            {"order_id", type text},
				            {"sentiment", type text},
				            {"topic", type text},
				            {"urgency", type text},
				            {"summary_en", type text},
				            {"provider", type text}
				        },
				        "en-US"
				    ),
				    WithKey = Table.AddColumn(Typed, "review_key", each [review_id] & "|" & [order_id], type text),
				    Result = WithKey
				in
				    Result
