"""Step 4 - How good is the AI? Measure it instead of trusting it.

Two checks:
 1. Sentiment vs the customer's own star rating (1-2 = negative, 3 = neutral,
    4-5 = positive) on ALL labelled reviews - free ground truth.
 2. Sentiment AND topic vs 150 hand-labelled reviews (data/eval/gold_labels.csv).

Compares every provider you have run (e.g. rules baseline vs Ollama).
Output: results/evaluation.md
"""
import sqlite3
import sys
from pathlib import Path

import pandas as pd
from sklearn.metrics import accuracy_score, confusion_matrix, f1_score

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
from src.config import DB_PATH, EVAL_DIR, PROCESSED_DIR, RESULTS_DIR
from src.labels import SENTIMENTS, TOPICS, stars_to_sentiment


def score(y_true, y_pred) -> tuple[float, float]:
    return accuracy_score(y_true, y_pred), f1_score(y_true, y_pred, average="macro", zero_division=0)


def main() -> None:
    gold = pd.read_csv(EVAL_DIR / "gold_labels.csv")
    con = sqlite3.connect(DB_PATH)
    stars = pd.read_sql_query("SELECT review_id, order_id, review_score FROM fact_reviews", con)
    con.close()

    files = sorted(PROCESSED_DIR.glob("review_labels_*.csv"))
    if not files:
        sys.exit("No labels yet - run scripts/03_label_reviews.py first.")

    summary, details = [], []
    for f in files:
        provider = f.stem.replace("review_labels_", "")
        labels = pd.read_csv(f)

        s = labels.merge(stars, on=["review_id", "order_id"])
        s["star_sentiment"] = s.review_score.apply(stars_to_sentiment)
        star_acc, star_f1 = score(s.star_sentiment, s.sentiment)

        g = gold.merge(labels, on=["review_id", "order_id"])
        g_sent_acc, g_sent_f1 = score(g.gold_sentiment, g.sentiment)
        g_topic_acc, g_topic_f1 = score(g.gold_topic, g.topic)
        neg = g[g.gold_sentiment == "negative"]
        neg_topic_acc = accuracy_score(neg.gold_topic, neg.topic) if len(neg) else float("nan")

        summary.append({
            "provider": provider, "labelled": len(labels),
            "sentiment_vs_stars_acc": star_acc, "sentiment_vs_stars_f1": star_f1,
            "gold_n": len(g), "gold_sentiment_acc": g_sent_acc,
            "gold_topic_acc": g_topic_acc, "gold_topic_macro_f1": g_topic_f1,
            "complaint_topic_acc": neg_topic_acc,
        })

        cm = pd.DataFrame(confusion_matrix(g.gold_topic, g.topic, labels=list(TOPICS)),
                          index=list(TOPICS), columns=list(TOPICS))
        cm = cm.loc[(cm.sum(axis=1) > 0) | (cm.sum(axis=0) > 0)]
        errors = g[g.gold_topic != g.topic][["comment_message", "gold_topic", "topic"]].head(8)
        errors["comment_message"] = errors.comment_message.str.slice(0, 90)
        details += [
            f"\n## {provider}: topic confusion matrix (rows = human label, columns = {provider})\n",
            cm.to_markdown(), "",
            f"\n### {provider}: example disagreements (review these by hand!)\n",
            errors.to_markdown(index=False), "",
        ]

    table = pd.DataFrame(summary)
    pct = [c for c in table.columns if c.endswith(("acc", "f1"))]
    shown = table.copy()
    shown[pct] = (shown[pct] * 100).round(1)
    md = [
        "# AI labelling evaluation\n",
        "_Generated by `scripts/04_evaluate.py`. Percentages._\n",
        "* **sentiment_vs_stars**: AI sentiment vs the customer's star rating (all labelled reviews).",
        "* **gold_***: vs 150 hand-labelled reviews (`data/eval/gold_labels.csv`).",
        "* **complaint_topic_acc**: topic accuracy on the negative reviews only - what the business acts on.\n",
        shown.to_markdown(index=False), "",
        *details,
    ]
    (RESULTS_DIR / "evaluation.md").write_text("\n".join(md), encoding="utf-8")
    table.to_csv(RESULTS_DIR / "evaluation_summary.csv", index=False)
    print(shown.to_string(index=False))
    print(f"\nFull report: {RESULTS_DIR / 'evaluation.md'}")


if __name__ == "__main__":
    main()
