"""Run every query in sql/02_analysis_queries.sql and save the results.

Outputs: results/sql/<query_name>.csv and results/sql_findings.md
"""
import re
import sqlite3
import sys
from pathlib import Path

import pandas as pd

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
from src.config import DB_PATH, RESULTS_DIR, ROOT


def parse_queries(text: str) -> list[tuple[str, str, str]]:
    """Split the .sql file on '-- name:' markers -> (name, question, sql)."""
    blocks = re.split(r"^-- name:\s*", text, flags=re.M)[1:]
    out = []
    for block in blocks:
        name, _, body = block.partition("\n")
        question = next((l[3:].strip() for l in body.splitlines() if l.startswith("-- Q")), "")
        sql = "\n".join(l for l in body.splitlines() if not l.strip().startswith("--")).strip()
        out.append((name.strip(), question, sql.rstrip(";")))
    return out


def main() -> None:
    out_dir = RESULTS_DIR / "sql"
    out_dir.mkdir(exist_ok=True)
    con = sqlite3.connect(DB_PATH)
    has_labels = con.execute("SELECT COUNT(*) FROM review_ai_labels").fetchone()[0] > 0
    md = ["# SQL findings\n", "_Generated by `scripts/run_sql_analysis.py`._\n"]
    for name, question, sql in parse_queries((ROOT / "sql" / "02_analysis_queries.sql").read_text()):
        if "review_ai_labels" in sql and not has_labels:
            print(f"skip {name} (run the AI labelling step first)")
            continue
        df = pd.read_sql_query(sql, con)
        df.to_csv(out_dir / f"{name}.csv", index=False)
        md += [f"\n## {question}\n", df.to_markdown(index=False, floatfmt=",.2f"), ""]
        print(f"ok   {name:<40} {len(df)} rows")
    (RESULTS_DIR / "sql_findings.md").write_text("\n".join(md), encoding="utf-8")
    con.close()


if __name__ == "__main__":
    main()
